#!/usr/bin/env bash
#PBS -q omp
#PBS -l ncpus=
#PBS -l walltime=36:00:00
#PBS -l mem= g
#PBS -N 15_raXml_invariant

DATADIRECTORY=path/to/working/directory
DATAINPUT=$DATADIRECTORY/06_SNP_Alignment
DATAOUTPUT=$DATADIRECTORY/07_RAxML_analysis
raxmlENV="path to RAxML executable"

mkdir -p $DATAOUTPUT

$raxmlENV
cd $DATAINPUT

raxmlHPC-PTHREADS -T 50 -f a -s PI2_for_RAxML.phy -w $DATAOUTPUT -n PI2_RAxML -p 123456 -x 123458 -# 1000 -m ASC_GTRGAMMA --asc-corr=lewis
conda deactivate